; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html



[platformio]
default_envs = arduino_nano_esp32

[common]
build_flags = -DCORE_DEBUG_LEVEL=3 '-Wall' '-std=gnu++17'

[env]
monitor_speed = 115200
upload_speed = 921600
board_build.f_cpu = 80000000L
platform = espressif32
framework = arduino
build_unflags = '-std=gnu++11'
build_flags = ${common.build_flags}
board_build.partitions = huge_app.csv
lib_deps = 
	adafruit/Adafruit BME280 Library @ 2.3.0
	adafruit/Adafruit BME680 Library @ 2.0.5
	adafruit/Adafruit BusIO @ 1.17.1
	adafruit/Adafruit Unified Sensor @ 1.1.15
	bblanchon/ArduinoJson @ 7.4.1
	zinggjm/GxEPD2 @ 1.6.4

[env:arduino_nano_esp32]
platform = espressif32@6.11.0
board = arduino_nano_esp32
build_flags = ${common.build_flags} -DARDUINO_NANO_ESP32


[env:dfrobot_firebeetle2_esp32e]
board = dfrobot_firebeetle2_esp32e
build_flags = ${common.build_flags} -DDFROBOT_FIREBEETLE2_ESP32E

[env:firebeetle32]
board = firebeetle32
build_flags = ${common.build_flags} -DFIREBEETLE32

[env:az_delivery_espressif32]
board = nodemcu-32s
build_flags = ${common.build_flags} -DAZ_DELIVERY_ESPRESSIF32

[env:waveshare_esp32]
board = esp32dev
build_flags = ${common.build_flags} -DWAVESHARE_ESP32
