; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html



[platformio]
default_envs = waveshare_esp32_c6zero

[common]
build_flags = '-Wall' 
	'-std=gnu++17'
	-D CORE_DEBUG_LEVEL=4
	-D LOG_TAG=\"epd-weather\"
	-D LOG_LOCAL_LEVEL=ESP_LOG_DEBUG
	-D CONFIG_LOG_VERSION=2
	-D CONFIG_LOG_COLORS_SUPPORT
	-D CONFIG_LOG_COLORS
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1  	

build_unflags = '-Werror' '-std=gnu++11' -D CONFIG_LOG_VERSION

[env]
monitor_speed = 115200
upload_speed = 921600
board_build.f_cpu = 80000000L
platform = espressif32 @ 6.13.0
framework = arduino
build_unflags = ${common.build_unflags}
build_flags = ${common.build_flags}
board_build.partitions = huge_app.csv
lib_deps =
  adafruit/Adafruit BME280 Library @ 2.3.0
  adafruit/Adafruit BME680 Library @ 2.0.6
  adafruit/Adafruit BusIO @ 1.17.4
  adafruit/Adafruit Unified Sensor @ 1.1.15
  bblanchon/ArduinoJson @ 7.4.3
  zinggjm/GxEPD2 @ 1.6.8

; ==============================================================================

; ; https://www.waveshare.com/wiki/ESP32-S3-Zero
; [env:waveshare_esp32s3zero]
; board = esp32-s3-devkitc-1
; board_build.flash_mode = qio
; board_build.psram_type = qio
; board_upload.flash_size = 4MB
; board_upload.maximum_size = 4194304
; build_flags = ${common.build_flags} 
; 	-D LOCAL_CONFIG_FILE=config/waveshare-esp32s3-zero.h
; 	-D LOCATION_CONFIG_FILE=config/locations/zurigo.cpp
; 	-D ARDUINO_USB_MODE=1
; 	-D ARDUINO_USB_CDC_ON_BOOT=1  
; build_unflags = ${common.build_unflags} 
; 	-D HAS_BUILTIN_LED

; ==============================================================================

[env:waveshare_esp32_c6zero]
platform = https://github.com/pioarduino/platform-espressif32.git
board = esp32-c6-devkitm-1
build_flags =
	${common.build_flags}
	-D HAS_BUILTIN_LED
	-D LOCAL_CONFIG_FILE=config/waveshare-esp32-c6.h
	-D LOCATION_CONFIG_FILE=config/locations/zurigo.cpp	
build_unflags = ${common.build_unflags}


; ==============================================================================

; https://wiki.seeedstudio.com/xiao_esp32c6_with_platform_io/
; Using pioarduino/espressif32 which has proper ESP32-C6 support
[env:seeed_xiao_esp32_c6]
platform = https://github.com/pioarduino/platform-espressif32.git
board = seeed_xiao_esp32c6
build_flags =
	${common.build_flags}
	-D HAS_BUILTIN_LED
	-D LOCAL_CONFIG_FILE=config/seedstudio-esp32-c6.h
	-D LOCATION_CONFIG_FILE=config/locations/zurigo.cpp	
build_unflags = ${common.build_unflags}

; ==============================================================================

[env:dfrobot_firebeetle2_esp32e]
board = dfrobot_firebeetle2_esp32e
build_flags =
	${common.build_flags}
	-D HAS_BUILTIN_LED
build_unflags = ${common.build_unflags}

; ==============================================================================

[env:firebeetle32]
board = firebeetle32
build_flags =
	${common.build_flags}
	-D HAS_BUILTIN_LED
build_unflags = ${common.build_unflags}